import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppProvider } from "./context/AppContext";
export const metadata = {
  title: "MB Perfume",
  description: "Generated by create next app",
};
import ToastProvider from "./_components/ToastProvider";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <ToastProvider />
        <AppProvider>{children} </AppProvider>
      </body>
    </html>
  );
}
